# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.4
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2024-04-05T07:06:45Z"
  name: volweb
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-04-05T07:06:45Z"
  labels:
    app: webserver2-pod
  name: webserver2-pod
spec:
  ports:
  - name: "8080"
    nodePort: 32389
    port: 8080
    targetPort: 8080
  selector:
    app: webserver2-pod
  type: NodePort
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-05T07:06:45Z"
  labels:
    app: webserver2-pod
  name: webserver2-pod
spec:
  containers:
  - args:
    - /usr/bin/run-httpd
    image: quay.io/fedora/httpd-24:2.4
    name: webserver2
    ports:
    - containerPort: 8080
    securityContext:
      runAsNonRoot: true
    volumeMounts:
    - mountPath: /var/www/html
      name: volweb-pvc
  volumes:
  - name: volweb-pvc
    persistentVolumeClaim:
      claimName: volweb
