version: '3.1'
services:
  app:
    container_name: guestbook
    image: docker.io/iesgn/guestbook
    restart: always
    environment:
      REDIS_SERVER: 10.0.0.231
      NETWORK_INTERFACE: tap0
    ports:
      - 8080:5000
    network_mode: "slirp4netns:port_handler=slirp4netns"
  db:
    container_name: redis
    image: docker.io/redis
    restart: always
    command: redis-server --appendonly yes
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    network_mode: "slirp4netns:port_handler=slirp4netns"
    environment:
      - NETWORK_INTERFACE=tap0
volumes:
  redis:
