version: '3.1'
services:
  app:
    network_mode: "slirp4netns:port_handler=slirp4netns"
    environment:
      - NETWORK_INTERFACE=tap0
    container_name: webserver
    image: quay.io/libpod/banner
    restart: always
    ports:
      - 8085:80
