# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.9.4
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2024-04-06T19:48:21Z"
  name: wpvol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.podman.io/driver: local
  creationTimestamp: "2024-04-06T19:48:21Z"
  name: dbvol
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-06T19:48:21Z"
  labels:
    app: wordpress-pod
  name: wordpress-pod
spec:
  containers:
  - args:
    - apache2-foreground
    env:
    - name: WORDPRESS_DB_HOST
      value: mariadb-pod
    - name: WORDPRESS_DB_PASSWORD
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_NAME
      value: wordpress
    image: docker.io/library/wordpress:latest
    name: wordpress
    ports:
    - containerPort: 80
      hostPort: 8080
    volumeMounts:
    - mountPath: /var/www/html
      name: wpvol-pvc
  volumes:
  - name: wpvol-pvc
    persistentVolumeClaim:
      claimName: wpvol
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-04-06T19:48:21Z"
  labels:
    app: mariadb-pod
  name: mariadb-pod
spec:
  containers:
  - args:
    - mariadbd
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: myrootpasswd
    - name: MARIADB_USER
      value: wordpress
    - name: MARIADB_PASSWORD
      value: wordpress
    - name: MARIADB_DATABASE
      value: wordpress
    image: docker.io/library/mariadb:latest
    name: db
    ports:
    - containerPort: 3306
      hostPort: 3306
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: dbvol-pvc
  volumes:
  - name: dbvol-pvc
    persistentVolumeClaim:
      claimName: dbvol
