apiVersion: v1
kind: Pod
metadata:
  labels:
    app: wordpress-pod
  name: wordpress-pod
spec:
  containers:
  - args:
    - mariadb
    env:
    - name: MARIADB_USER
      value: wordpress
    - name: MARIADB_ROOT_PASSWORD
      value: myrootpasswd
    - name: MARIADB_DATABASE
      value: wordpress
    - name: MARIADB_PASSWORD
      value: wordpress
    image: docker.io/library/mariadb:latest
    name: db
    ports:
    - containerPort: 80
      hostPort: 8080
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: dbvol-pvc
  - args:
    - apache2-foreground
    env:
    - name: WORDPRESS_DB_PASSWORD
      value: wordpress
    - name: WORDPRESS_DB_USER
      value: wordpress
    - name: WORDPRESS_DB_NAME
      value: wordpress
    - name: WORDPRESS_DB_HOST
      value: 127.0.0.1
    image: docker.io/library/wordpress:latest
    name: wordpress
    resources: {}
    securityContext:
      capabilities:
        drop:
        - CAP_MKNOD
        - CAP_NET_RAW
        - CAP_AUDIT_WRITE
    volumeMounts:
    - mountPath: /var/www/html
      name: wpvol-pvc
  restartPolicy: Never
  volumes:
  - name: wpvol-pvc
    persistentVolumeClaim:
      claimName: wpvol
  - name: dbvol-pvc
    persistentVolumeClaim:
      claimName: dbvol
status: {}
